server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Nome bonito do container
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        regex: "/(.*)"
        replacement: "$1"

      # Nome do servi√ßo do docker-compose
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      # Arquivo de log real
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [__meta_docker_container_image]
        target_label: image

      # Caminho do arquivo de log
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
